name: nu_pogodi
description: A wolf has to collect as many eggs as he can.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.1
  flame_audio: ^2.0.5
  shared_preferences: ^2.2.0
  google_mobile_ads: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/zajacOkno.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    
  fonts:
    - family: digits
      fonts:
        - asset: assets/fonts/DISPLAY_FREE_TFB.ttf
    - family: niceTango
      fonts:
        - asset: assets/fonts/Nice_Tango.ttf
       